# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from label import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 706)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_img = MyLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_img.sizePolicy().hasHeightForWidth())
        self.label_img.setSizePolicy(sizePolicy)
        self.label_img.setMinimumSize(QtCore.QSize(641, 641))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_img.setFont(font)
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.horizontalLayout.addWidget(self.label_img)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(250, 0))
        self.frame.setMaximumSize(QtCore.QSize(240, 640))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Button_camera = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_camera.sizePolicy().hasHeightForWidth())
        self.Button_camera.setSizePolicy(sizePolicy)
        self.Button_camera.setMinimumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_camera.setFont(font)
        self.Button_camera.setObjectName("Button_camera")
        self.verticalLayout.addWidget(self.Button_camera)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(240, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Button_from_src = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_from_src.sizePolicy().hasHeightForWidth())
        self.Button_from_src.setSizePolicy(sizePolicy)
        self.Button_from_src.setMinimumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_from_src.setFont(font)
        self.Button_from_src.setObjectName("Button_from_src")
        self.verticalLayout.addWidget(self.Button_from_src)
        self.Button_from_strong = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_from_strong.sizePolicy().hasHeightForWidth())
        self.Button_from_strong.setSizePolicy(sizePolicy)
        self.Button_from_strong.setMinimumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_from_strong.setFont(font)
        self.Button_from_strong.setObjectName("Button_from_strong")
        self.verticalLayout.addWidget(self.Button_from_strong)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(240, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.Button_change_illu = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_change_illu.sizePolicy().hasHeightForWidth())
        self.Button_change_illu.setSizePolicy(sizePolicy)
        self.Button_change_illu.setMinimumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_change_illu.setFont(font)
        self.Button_change_illu.setObjectName("Button_change_illu")
        self.verticalLayout.addWidget(self.Button_change_illu)
        self.horizontalSlider = QtWidgets.QSlider(self.frame)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(240, 0))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.Button_change_color = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_change_color.sizePolicy().hasHeightForWidth())
        self.Button_change_color.setSizePolicy(sizePolicy)
        self.Button_change_color.setMinimumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_change_color.setFont(font)
        self.Button_change_color.setObjectName("Button_change_color")
        self.verticalLayout.addWidget(self.Button_change_color)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(240, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_fore_color = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_fore_color.sizePolicy().hasHeightForWidth())
        self.Button_fore_color.setSizePolicy(sizePolicy)
        self.Button_fore_color.setMinimumSize(QtCore.QSize(50, 30))
        self.Button_fore_color.setObjectName("Button_fore_color")
        self.horizontalLayout_2.addWidget(self.Button_fore_color)
        self.label_color = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_color.sizePolicy().hasHeightForWidth())
        self.label_color.setSizePolicy(sizePolicy)
        self.label_color.setMinimumSize(QtCore.QSize(50, 30))
        self.label_color.setText("")
        self.label_color.setObjectName("label_color")
        self.horizontalLayout_2.addWidget(self.label_color)
        self.Button_gray_back = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_gray_back.sizePolicy().hasHeightForWidth())
        self.Button_gray_back.setSizePolicy(sizePolicy)
        self.Button_gray_back.setMinimumSize(QtCore.QSize(50, 30))
        self.Button_gray_back.setObjectName("Button_gray_back")
        self.horizontalLayout_2.addWidget(self.Button_gray_back)
        self.Button_blur_back = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_blur_back.sizePolicy().hasHeightForWidth())
        self.Button_blur_back.setSizePolicy(sizePolicy)
        self.Button_blur_back.setMinimumSize(QtCore.QSize(50, 30))
        self.Button_blur_back.setObjectName("Button_blur_back")
        self.horizontalLayout_2.addWidget(self.Button_blur_back)
        self.verticalLayout.addWidget(self.frame_2)
        self.Button_poisson = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_poisson.sizePolicy().hasHeightForWidth())
        self.Button_poisson.setSizePolicy(sizePolicy)
        self.Button_poisson.setMinimumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button_poisson.setFont(font)
        self.Button_poisson.setObjectName("Button_poisson")
        self.verticalLayout.addWidget(self.Button_poisson)
        self.horizontalLayout.addWidget(self.frame)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_dst_img = QtWidgets.QAction(MainWindow)
        self.action_dst_img.setObjectName("action_dst_img")
        self.action_src_img = QtWidgets.QAction(MainWindow)
        self.action_src_img.setObjectName("action_src_img")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.menuOpen.addAction(self.action_dst_img)
        self.menuOpen.addAction(self.action_src_img)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.action_save_as)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_camera.setText(_translate("MainWindow", "Camera"))
        self.label_2.setText(_translate("MainWindow", "Guidance field"))
        self.Button_from_src.setText(_translate("MainWindow", "Source image"))
        self.Button_from_strong.setText(_translate("MainWindow", "Stronger"))
        self.label_3.setText(_translate("MainWindow", "Local changes"))
        self.Button_change_illu.setText(_translate("MainWindow", "Illumination changes"))
        self.Button_change_color.setText(_translate("MainWindow", "Color changes"))
        self.Button_fore_color.setText(_translate("MainWindow", "Fore"))
        self.Button_gray_back.setText(_translate("MainWindow", "Gray"))
        self.Button_blur_back.setText(_translate("MainWindow", "Blur"))
        self.Button_poisson.setText(_translate("MainWindow", "Poisson Image Editing"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.action_dst_img.setText(_translate("MainWindow", "dst image"))
        self.action_src_img.setText(_translate("MainWindow", "src image"))
        self.action_save_as.setText(_translate("MainWindow", "Save"))
